export interface Chain {
  uniq(...args: any[]): Chain;
  shuffle(...args: any[]): Chain;
  take(...args: any[]): Chain;
  takeRight(...args: any[]): Chain;
  drop(...args: any[]): Chain;
  dropRight(...args: any[]): Chain;
  chunk(...args: any[]): Chain;
  flatten(...args: any[]): Chain;
  compact(...args: any[]): Chain;
  union(...args: any[]): Chain;
  intersection(...args: any[]): Chain;
  difference(...args: any[]): Chain;
  groupBy(...args: any[]): Chain;
  sortBy(...args: any[]): Chain;
  pluck(...args: any[]): Chain;
  first(...args: any[]): Chain;
  last(...args: any[]): Chain;
  value(): any;
}

export function abs(...args: any[]): any;
export function acosDeg(...args: any[]): any;
export function add(...args: any[]): any;
export function anyOf(...args: any[]): boolean;
export function apothemRegularPolygon(...args: any[]): any;
export function arcLength(...args: any[]): number;
export function areaCircle(...args: any[]): number;
export function areaEllipse(...args: any[]): number;
export function areaParallelogram(...args: any[]): number;
export function areaRectangle(...args: any[]): number;
export function areaRegularPolygon(...args: any[]): any;
export function areaRing(...args: any[]): number;
export function areaSector(...args: any[]): number;
export function areaSquare(...args: any[]): number;
export function areaTrapezoid(...args: any[]): number;
export function areaTriangle(...args: any[]): number;
export function arrayFromArgs(...args: any[]): any;
export function arrayGroupBy(...args: any[]): any;
export function asArray(...args: any[]): any;
export function asinDeg(...args: any[]): any;
export function atanDeg(...args: any[]): any;
export function averageOfThree(...args: any[]): any;
export function averageOfTwo(...args: any[]): any;
export function avg(...args: any[]): number;
export function avgBy(...args: any[]): any;
export function between(...args: any[]): boolean;
export function camelCase(...args: any[]): any;
export function capitalize(...args: any[]): any;
export function cbrt(...args: any[]): any;
export function ceilTo(...args: any[]): any;
export function ceilToMultiple(...args: any[]): any;
export function chain(value: any): Chain;
export function chunk(...args: any[]): any;
export function chunkBy(...args: any[]): any;
export function chunkWhile(...args: any[]): any;
export function circumferenceCircle(...args: any[]): number;
export function circumradiusRegularPolygon(...args: any[]): any;
export function clamp(...args: any[]): number;
export function clamp01(...args: any[]): number;
export function clampAbs(...args: any[]): any;
export function clampInt(...args: any[]): any;
export function clampMax(...args: any[]): any;
export function clampMin(...args: any[]): any;
export function clampPercent(...args: any[]): any;
export function cloneShallow(...args: any[]): any;
export function collapseWhitespace(...args: any[]): any;
export function compact(...args: any[]): any;
export function compactBy(...args: any[]): any;
export function compose(...args: any[]): any;
export function containsAny(...args: any[]): boolean;
export function convertCtoF(...args: any[]): any;
export function convertCtoK(...args: any[]): any;
export function convertFtoC(...args: any[]): any;
export function convertFtoK(...args: any[]): any;
export function convertKtoC(...args: any[]): any;
export function convertKtoF(...args: any[]): any;
export function cosDeg(...args: any[]): any;
export function count(...args: any[]): any;
export function countBy(...args: any[]): any;
export function countChars(...args: any[]): any;
export function countOccurrences(...args: any[]): any;
export function countWords(...args: any[]): any;
export function cube(...args: any[]): any;
export function debounce(...args: any[]): any;
export function deepClone(...args: any[]): any;
export function deepMerge(...args: any[]): any;
export function defaultTo(...args: any[]): any;
export function defaults(...args: any[]): any;
export function defaultsDeep(...args: any[]): any;
export function defer(...args: any[]): any;
export function degToRad(...args: any[]): any;
export function degToTurn(...args: any[]): any;
export function denormalize(...args: any[]): any;
export function diff(...args: any[]): any;
export function difference(...args: any[]): any;
export function differenceBy(...args: any[]): any;
export function distance1D(...args: any[]): any;
export function distance2D(...args: any[]): any;
export function distance3D(...args: any[]): any;
export function distancePointLine(...args: any[]): any;
export function distancePoints(...args: any[]): number;
export function divide(...args: any[]): any;
export function dot2(...args: any[]): any;
export function dot3(...args: any[]): any;
export function drop(...args: any[]): any;
export function dropRight(...args: any[]): any;
export function dropUntil(...args: any[]): any;
export function dropWhile(...args: any[]): any;
export function endsWith(...args: any[]): boolean;
export function endsWithAny(...args: any[]): boolean;
export function ensurePrefix(...args: any[]): any;
export function ensureSuffix(...args: any[]): any;
export function entries(...args: any[]): any;
export function eqAny(...args: any[]): boolean;
export function exp(...args: any[]): any;
export function expm1(...args: any[]): any;
export function factorial(...args: any[]): any;
export function fibonacci(...args: any[]): any;
export function filterKeys(...args: any[]): any;
export function filterValues(...args: any[]): any;
export function findLast(...args: any[]): any;
export function findLastIndex(...args: any[]): any;
export function first(...args: any[]): any;
export function flatten(...args: any[]): any;
export function flattenDeep(...args: any[]): any;
export function flattenDepth(...args: any[]): any;
export function floorTo(...args: any[]): any;
export function floorToMultiple(...args: any[]): any;
export function fromEntries(...args: any[]): any;
export function fromPairs(...args: any[]): any;
export function fromPercent(...args: any[]): number;
export function fromSet(...args: any[]): any;
export function gcd(...args: any[]): any;
export function geometricMean(...args: any[]): any;
export function groupBy(...args: any[]): any;
export function harmonicMean(...args: any[]): any;
export function has(...args: any[]): boolean;
export function hasPath(...args: any[]): any;
export function head(...args: any[]): any;
export function heronArea(...args: any[]): number;
export function hypot2(...args: any[]): any;
export function hypot3(...args: any[]): any;
export function identity(...args: any[]): any;
export function inArray(...args: any[]): boolean;
export function inRangeExclusive(...args: any[]): boolean;
export function inRangeInclusive(...args: any[]): boolean;
export function includes(...args: any[]): boolean;
export function indexBy(...args: any[]): any;
export function indexOfAll(...args: any[]): any;
export function init(...args: any[]): any;
export function insertAt(...args: any[]): any;
export function use(plugin: (easy: typeof easyJS) => void): typeof easyJS;
export function install(): void;
export function intersection(...args: any[]): any;
export function intersectionBy(...args: any[]): any;
export function invert(...args: any[]): any;
export function invertBy(...args: any[]): any;
export function isArray(...args: any[]): boolean;
export function isBlank(...args: any[]): boolean;
export function isEmpty(...args: any[]): boolean;
export function isEmptyObject(...args: any[]): any;
export function isEven(...args: any[]): boolean;
export function isFiniteNumber(...args: any[]): boolean;
export function isInt(...args: any[]): boolean;
export function isLower(...args: any[]): any;
export function isMultipleOf(...args: any[]): boolean;
export function isNaNNumber(...args: any[]): boolean;
export function isNegative(...args: any[]): boolean;
export function isNil(...args: any[]): boolean;
export function isNumber(...args: any[]): boolean;
export function isObject(...args: any[]): any;
export function isOdd(...args: any[]): boolean;
export function isPositive(...args: any[]): boolean;
export function isPowerOfTwo(...args: any[]): boolean;
export function isPrime(...args: any[]): boolean;
export function isUpper(...args: any[]): any;
export function isZero(...args: any[]): boolean;
export function kebabCase(...args: any[]): any;
export function keyBy(...args: any[]): any;
export function keys(...args: any[]): any;
export function last(...args: any[]): any;
export function lastIndex(...args: any[]): any;
export function lastIndexOf(...args: any[]): any;
export function lawOfCosinesAngle(...args: any[]): any;
export function lawOfCosinesSide(...args: any[]): any;
export function lawOfSinesAngle(...args: any[]): any;
export function lawOfSinesSide(...args: any[]): any;
export function lcm(...args: any[]): any;
export function lerp(...args: any[]): number;
export function lerpAngleDeg(...args: any[]): any;
export function lerpAngleRad(...args: any[]): any;
export function lerpClamped(...args: any[]): any;
export function lerpInt(...args: any[]): any;
export function lines(...args: any[]): any;
export function ln1p(...args: any[]): any;
export function log(...args: any[]): any;
export function log10(...args: any[]): any;
export function log2(...args: any[]): any;
export function manhattan2D(...args: any[]): any;
export function manhattan3D(...args: any[]): any;
export function mapEntries(...args: any[]): any;
export function mapKeys(...args: any[]): any;
export function mapRange(...args: any[]): any;
export function mapValues(...args: any[]): any;
export function mask(...args: any[]): any;
export function max(...args: any[]): number;
export function mean(...args: any[]): any;
export function median(...args: any[]): number;
export function medianOfThree(...args: any[]): any;
export function memoize(...args: any[]): any;
export function merge(...args: any[]): any;
export function mergeWith(...args: any[]): any;
export function midpointX(...args: any[]): number;
export function midpointY(...args: any[]): number;
export function min(...args: any[]): number;
export function mod(...args: any[]): any;
export function modSafe(...args: any[]): any;
export function mode(...args: any[]): number;
export function move(...args: any[]): any;
export function multiply(...args: any[]): any;
export function nCr(...args: any[]): any;
export function nPr(...args: any[]): any;
export function nearEqual(...args: any[]): boolean;
export function nextPrime(...args: any[]): any;
export function noop(...args: any[]): any;
export function noopAsync(...args: any[]): any;
export function normalize(...args: any[]): any;
export function normalizeAngle(...args: any[]): any;
export function normalizeString(...args: any[]): any;
export function objectCompact(...args: any[]): any;
export function omit(...args: any[]): any;
export function omitBy(...args: any[]): any;
export function omitPath(...args: any[]): any;
export function once(...args: any[]): any;
export function onceAsync(...args: any[]): any;
export function padCenter(...args: any[]): any;
export function padLeft(...args: any[]): any;
export function padRight(...args: any[]): any;
export function parsePath(...args: any[]): any;
export function partition(...args: any[]): any;
export function pascalCase(...args: any[]): any;
export function percent(...args: any[]): number;
export function percentChange(...args: any[]): any;
export function percentOf(...args: any[]): number;
export function percentile(...args: any[]): number;
export function perimeterRectangle(...args: any[]): number;
export function perimeterRegularPolygon(...args: any[]): any;
export function perimeterSquare(...args: any[]): number;
export function perimeterTriangle(...args: any[]): number;
export function pick(...args: any[]): any;
export function pickBy(...args: any[]): any;
export function pickPath(...args: any[]): any;
export function pingPong(...args: any[]): any;
export function pipe(...args: any[]): any;
export function pluck(...args: any[]): any;
export function pow(...args: any[]): any;
export function prevPrime(...args: any[]): any;
export function pythagoras(...args: any[]): number;
export function quadraticDiscriminant(...args: any[]): number;
export function quadraticRoots(...args: any[]): any;
export function radToDeg(...args: any[]): any;
export function radToTurn(...args: any[]): any;
export function randomBool(...args: any[]): any;
export function randomFloat(...args: any[]): number;
export function randomGaussian(...args: any[]): any;
export function randomInt(...args: any[]): number;
export function randomSign(...args: any[]): any;
export function range(...args: any[]): any;
export function ratio(...args: any[]): any;
export function removeAt(...args: any[]): any;
export function removeConsonants(...args: any[]): any;
export function removeVowels(...args: any[]): any;
export function repeat(...args: any[]): any;
export function repeatArray(...args: any[]): any;
export function replaceAll(...args: any[]): any;
export function replaceFirst(...args: any[]): any;
export function replaceLast(...args: any[]): any;
export function reverseString(...args: any[]): any;
export function rms(...args: any[]): any;
export function rotate(...args: any[]): any;
export function rotateLeft(...args: any[]): any;
export function rotateRight(...args: any[]): any;
export function roundBankers(...args: any[]): any;
export function roundDecimal(...args: any[]): number;
export function roundDown(...args: any[]): number;
export function roundHalfDown(...args: any[]): any;
export function roundHalfUp(...args: any[]): any;
export function roundTo(...args: any[]): number;
export function roundToMultiple(...args: any[]): any;
export function roundToNearest(...args: any[]): any;
export function roundToSignificant(...args: any[]): any;
export function roundToStep(...args: any[]): any;
export function roundUp(...args: any[]): number;
export function safeDivide(...args: any[]): any;
export function safeGet(...args: any[]): any;
export function safeJsonParse(...args: any[]): any;
export function safeJsonStringify(...args: any[]): any;
export function safeSet(...args: any[]): any;
export function sample(...args: any[]): any;
export function sawtoothWave(...args: any[]): any;
export function shuffle(...args: any[]): any;
export function sigmoid(...args: any[]): any;
export function sign(...args: any[]): any;
export function sinDeg(...args: any[]): any;
export function size(...args: any[]): any;
export function sleep(ms: number): Promise<void>;
export function slidingWindow(...args: any[]): any;
export function slope(...args: any[]): number;
export function slugify(...args: any[]): any;
export function smoothClamp(...args: any[]): any;
export function smootherstep(...args: any[]): any;
export function smoothstep(...args: any[]): any;
export function smoothstep01(...args: any[]): any;
export function snakeCase(...args: any[]): any;
export function sortBy(...args: any[]): any;
export function sqrt(...args: any[]): any;
export function square(...args: any[]): any;
export function startsWith(...args: any[]): boolean;
export function startsWithAny(...args: any[]): boolean;
export function stdDev(...args: any[]): any;
export function stdDevSample(...args: any[]): any;
export function step(...args: any[]): any;
export function stripNonAlpha(...args: any[]): any;
export function stripPrefix(...args: any[]): any;
export function stripSuffix(...args: any[]): any;
export function subtract(...args: any[]): any;
export function sum(...args: any[]): number;
export function sumBy(...args: any[]): any;
export function sumOfSquares(...args: any[]): any;
export function sumOfTwo(...args: any[]): any;
export function surfaceAreaCone(...args: any[]): number;
export function surfaceAreaCube(...args: any[]): number;
export function surfaceAreaCylinder(...args: any[]): number;
export function surfaceAreaPyramidSquare(...args: any[]): number;
export function surfaceAreaRectPrism(...args: any[]): number;
export function surfaceAreaSphere(...args: any[]): number;
export function surround(...args: any[]): any;
export function swap(...args: any[]): any;
export function swapCase(...args: any[]): any;
export function tail(...args: any[]): any;
export function take(...args: any[]): any;
export function takeRight(...args: any[]): any;
export function takeUntil(...args: any[]): any;
export function takeWhile(...args: any[]): any;
export function tanDeg(...args: any[]): any;
export function tap(...args: any[]): any;
export function throttle(...args: any[]): any;
export function times(...args: any[]): any;
export function toFloat(...args: any[]): number;
export function toInt(...args: any[]): number;
export function stringMerge(...args: any[]): string;
export function interleave(...args: any[]): string;
export function toLower(...args: any[]): any;
export function toNumber(...args: any[]): number;
export function toPairs(...args: any[]): any;
export function toSet(...args: any[]): any;
export function toTitleCase(...args: any[]): any;
export function toTitleCaseWords(...args: any[]): any;
export function toUpper(...args: any[]): any;
export function triangleWave(...args: any[]): any;
export function triangularNumber(...args: any[]): any;
export function trim(...args: any[]): any;
export function trimEnd(...args: any[]): any;
export function trimStart(...args: any[]): any;
export function truncate(...args: any[]): any;
export function tryCatch(...args: any[]): any;
export function turnToDeg(...args: any[]): any;
export function turnToRad(...args: any[]): any;
export function union(...args: any[]): any;
export function unionBy(...args: any[]): any;
export function uniq(...args: any[]): any;
export function uniqueBy(...args: any[]): any;
export function uniqueSorted(...args: any[]): any;
export function unmask(...args: any[]): any;
export function unsetPath(...args: any[]): any;
export function unzip(...args: any[]): any;
export function values(...args: any[]): any;
export function variance(...args: any[]): any;
export function varianceSample(...args: any[]): any;
export function volumeCone(...args: any[]): number;
export function volumeCube(...args: any[]): number;
export function volumeCylinder(...args: any[]): number;
export function volumePyramidSquare(...args: any[]): number;
export function volumeRectPrism(...args: any[]): number;
export function volumeSphere(...args: any[]): number;
export function words(...args: any[]): any;
export function wrap(...args: any[]): any;
export function wrapAngle(...args: any[]): any;
export function wrapPi(...args: any[]): any;
export function zip(...args: any[]): any;
export function zipObject(...args: any[]): any;
export function zipObjectDeep(...args: any[]): any;

declare const easyJS: {
  abs: typeof abs;
  acosDeg: typeof acosDeg;
  add: typeof add;
  anyOf: typeof anyOf;
  apothemRegularPolygon: typeof apothemRegularPolygon;
  arcLength: typeof arcLength;
  areaCircle: typeof areaCircle;
  areaEllipse: typeof areaEllipse;
  areaParallelogram: typeof areaParallelogram;
  areaRectangle: typeof areaRectangle;
  areaRegularPolygon: typeof areaRegularPolygon;
  areaRing: typeof areaRing;
  areaSector: typeof areaSector;
  areaSquare: typeof areaSquare;
  areaTrapezoid: typeof areaTrapezoid;
  areaTriangle: typeof areaTriangle;
  arrayFromArgs: typeof arrayFromArgs;
  arrayGroupBy: typeof arrayGroupBy;
  asArray: typeof asArray;
  asinDeg: typeof asinDeg;
  atanDeg: typeof atanDeg;
  averageOfThree: typeof averageOfThree;
  averageOfTwo: typeof averageOfTwo;
  avg: typeof avg;
  avgBy: typeof avgBy;
  between: typeof between;
  camelCase: typeof camelCase;
  capitalize: typeof capitalize;
  cbrt: typeof cbrt;
  ceilTo: typeof ceilTo;
  ceilToMultiple: typeof ceilToMultiple;
  chain: typeof chain;
  chunk: typeof chunk;
  chunkBy: typeof chunkBy;
  chunkWhile: typeof chunkWhile;
  circumferenceCircle: typeof circumferenceCircle;
  circumradiusRegularPolygon: typeof circumradiusRegularPolygon;
  clamp: typeof clamp;
  clamp01: typeof clamp01;
  clampAbs: typeof clampAbs;
  clampInt: typeof clampInt;
  clampMax: typeof clampMax;
  clampMin: typeof clampMin;
  clampPercent: typeof clampPercent;
  cloneShallow: typeof cloneShallow;
  collapseWhitespace: typeof collapseWhitespace;
  compact: typeof compact;
  compactBy: typeof compactBy;
  compose: typeof compose;
  containsAny: typeof containsAny;
  convertCtoF: typeof convertCtoF;
  convertCtoK: typeof convertCtoK;
  convertFtoC: typeof convertFtoC;
  convertFtoK: typeof convertFtoK;
  convertKtoC: typeof convertKtoC;
  convertKtoF: typeof convertKtoF;
  cosDeg: typeof cosDeg;
  count: typeof count;
  countBy: typeof countBy;
  countChars: typeof countChars;
  countOccurrences: typeof countOccurrences;
  countWords: typeof countWords;
  cube: typeof cube;
  debounce: typeof debounce;
  deepClone: typeof deepClone;
  deepMerge: typeof deepMerge;
  defaultTo: typeof defaultTo;
  defaults: typeof defaults;
  defaultsDeep: typeof defaultsDeep;
  defer: typeof defer;
  degToRad: typeof degToRad;
  degToTurn: typeof degToTurn;
  denormalize: typeof denormalize;
  diff: typeof diff;
  difference: typeof difference;
  differenceBy: typeof differenceBy;
  distance1D: typeof distance1D;
  distance2D: typeof distance2D;
  distance3D: typeof distance3D;
  distancePointLine: typeof distancePointLine;
  distancePoints: typeof distancePoints;
  divide: typeof divide;
  dot2: typeof dot2;
  dot3: typeof dot3;
  drop: typeof drop;
  dropRight: typeof dropRight;
  dropUntil: typeof dropUntil;
  dropWhile: typeof dropWhile;
  endsWith: typeof endsWith;
  endsWithAny: typeof endsWithAny;
  ensurePrefix: typeof ensurePrefix;
  ensureSuffix: typeof ensureSuffix;
  entries: typeof entries;
  eqAny: typeof eqAny;
  exp: typeof exp;
  expm1: typeof expm1;
  factorial: typeof factorial;
  fibonacci: typeof fibonacci;
  filterKeys: typeof filterKeys;
  filterValues: typeof filterValues;
  findLast: typeof findLast;
  findLastIndex: typeof findLastIndex;
  first: typeof first;
  flatten: typeof flatten;
  flattenDeep: typeof flattenDeep;
  flattenDepth: typeof flattenDepth;
  floorTo: typeof floorTo;
  floorToMultiple: typeof floorToMultiple;
  fromEntries: typeof fromEntries;
  fromPairs: typeof fromPairs;
  fromPercent: typeof fromPercent;
  fromSet: typeof fromSet;
  gcd: typeof gcd;
  geometricMean: typeof geometricMean;
  groupBy: typeof groupBy;
  harmonicMean: typeof harmonicMean;
  has: typeof has;
  hasPath: typeof hasPath;
  head: typeof head;
  heronArea: typeof heronArea;
  hypot2: typeof hypot2;
  hypot3: typeof hypot3;
  identity: typeof identity;
  inArray: typeof inArray;
  inRangeExclusive: typeof inRangeExclusive;
  inRangeInclusive: typeof inRangeInclusive;
  includes: typeof includes;
  indexBy: typeof indexBy;
  indexOfAll: typeof indexOfAll;
    init: typeof init;
    insertAt: typeof insertAt;
    use: typeof use;
    install: typeof install;
  intersection: typeof intersection;
  intersectionBy: typeof intersectionBy;
  invert: typeof invert;
  invertBy: typeof invertBy;
  isArray: typeof isArray;
  isBlank: typeof isBlank;
  isEmpty: typeof isEmpty;
  isEmptyObject: typeof isEmptyObject;
  isEven: typeof isEven;
  isFiniteNumber: typeof isFiniteNumber;
  isInt: typeof isInt;
  isLower: typeof isLower;
  isMultipleOf: typeof isMultipleOf;
  isNaNNumber: typeof isNaNNumber;
  isNegative: typeof isNegative;
  isNil: typeof isNil;
  isNumber: typeof isNumber;
  isObject: typeof isObject;
  isOdd: typeof isOdd;
  isPositive: typeof isPositive;
  isPowerOfTwo: typeof isPowerOfTwo;
  isPrime: typeof isPrime;
  isUpper: typeof isUpper;
  isZero: typeof isZero;
  kebabCase: typeof kebabCase;
  keyBy: typeof keyBy;
  keys: typeof keys;
  last: typeof last;
  lastIndex: typeof lastIndex;
  lastIndexOf: typeof lastIndexOf;
  lawOfCosinesAngle: typeof lawOfCosinesAngle;
  lawOfCosinesSide: typeof lawOfCosinesSide;
  lawOfSinesAngle: typeof lawOfSinesAngle;
  lawOfSinesSide: typeof lawOfSinesSide;
  lcm: typeof lcm;
  lerp: typeof lerp;
  lerpAngleDeg: typeof lerpAngleDeg;
  lerpAngleRad: typeof lerpAngleRad;
  lerpClamped: typeof lerpClamped;
  lerpInt: typeof lerpInt;
  lines: typeof lines;
  ln1p: typeof ln1p;
  log: typeof log;
  log10: typeof log10;
  log2: typeof log2;
  manhattan2D: typeof manhattan2D;
  manhattan3D: typeof manhattan3D;
  mapEntries: typeof mapEntries;
  mapKeys: typeof mapKeys;
  mapRange: typeof mapRange;
  mapValues: typeof mapValues;
  mask: typeof mask;
  max: typeof max;
  mean: typeof mean;
  median: typeof median;
  medianOfThree: typeof medianOfThree;
  memoize: typeof memoize;
  merge: typeof merge;
  mergeWith: typeof mergeWith;
  midpointX: typeof midpointX;
  midpointY: typeof midpointY;
  min: typeof min;
  mod: typeof mod;
  modSafe: typeof modSafe;
  mode: typeof mode;
  move: typeof move;
  multiply: typeof multiply;
  nCr: typeof nCr;
  nPr: typeof nPr;
  nearEqual: typeof nearEqual;
  nextPrime: typeof nextPrime;
  noop: typeof noop;
  noopAsync: typeof noopAsync;
  normalize: typeof normalize;
  normalizeAngle: typeof normalizeAngle;
  normalizeString: typeof normalizeString;
  objectCompact: typeof objectCompact;
  omit: typeof omit;
  omitBy: typeof omitBy;
  omitPath: typeof omitPath;
  once: typeof once;
  onceAsync: typeof onceAsync;
  padCenter: typeof padCenter;
  padLeft: typeof padLeft;
  padRight: typeof padRight;
  parsePath: typeof parsePath;
  partition: typeof partition;
  pascalCase: typeof pascalCase;
  percent: typeof percent;
  percentChange: typeof percentChange;
  percentOf: typeof percentOf;
  percentile: typeof percentile;
  perimeterRectangle: typeof perimeterRectangle;
  perimeterRegularPolygon: typeof perimeterRegularPolygon;
  perimeterSquare: typeof perimeterSquare;
  perimeterTriangle: typeof perimeterTriangle;
  pick: typeof pick;
  pickBy: typeof pickBy;
  pickPath: typeof pickPath;
  pingPong: typeof pingPong;
  pipe: typeof pipe;
  pluck: typeof pluck;
  pow: typeof pow;
  prevPrime: typeof prevPrime;
  pythagoras: typeof pythagoras;
  quadraticDiscriminant: typeof quadraticDiscriminant;
  quadraticRoots: typeof quadraticRoots;
  radToDeg: typeof radToDeg;
  radToTurn: typeof radToTurn;
  randomBool: typeof randomBool;
  randomFloat: typeof randomFloat;
  randomGaussian: typeof randomGaussian;
  randomInt: typeof randomInt;
  randomSign: typeof randomSign;
  range: typeof range;
  ratio: typeof ratio;
  removeAt: typeof removeAt;
  removeConsonants: typeof removeConsonants;
  removeVowels: typeof removeVowels;
  repeat: typeof repeat;
  repeatArray: typeof repeatArray;
  replaceAll: typeof replaceAll;
  replaceFirst: typeof replaceFirst;
  replaceLast: typeof replaceLast;
  reverseString: typeof reverseString;
  rms: typeof rms;
  rotate: typeof rotate;
  rotateLeft: typeof rotateLeft;
  rotateRight: typeof rotateRight;
  roundBankers: typeof roundBankers;
  roundDecimal: typeof roundDecimal;
  roundDown: typeof roundDown;
  roundHalfDown: typeof roundHalfDown;
  roundHalfUp: typeof roundHalfUp;
  roundTo: typeof roundTo;
  roundToMultiple: typeof roundToMultiple;
  roundToNearest: typeof roundToNearest;
  roundToSignificant: typeof roundToSignificant;
  roundToStep: typeof roundToStep;
  roundUp: typeof roundUp;
  safeDivide: typeof safeDivide;
  safeGet: typeof safeGet;
  safeJsonParse: typeof safeJsonParse;
  safeJsonStringify: typeof safeJsonStringify;
  safeSet: typeof safeSet;
  sample: typeof sample;
  sawtoothWave: typeof sawtoothWave;
  shuffle: typeof shuffle;
  sigmoid: typeof sigmoid;
  sign: typeof sign;
  sinDeg: typeof sinDeg;
  size: typeof size;
  sleep: typeof sleep;
  slidingWindow: typeof slidingWindow;
  slope: typeof slope;
  slugify: typeof slugify;
  smoothClamp: typeof smoothClamp;
  smootherstep: typeof smootherstep;
  smoothstep: typeof smoothstep;
  smoothstep01: typeof smoothstep01;
  snakeCase: typeof snakeCase;
  sortBy: typeof sortBy;
  sqrt: typeof sqrt;
  square: typeof square;
  startsWith: typeof startsWith;
  startsWithAny: typeof startsWithAny;
  stdDev: typeof stdDev;
  stdDevSample: typeof stdDevSample;
  step: typeof step;
  stripNonAlpha: typeof stripNonAlpha;
  stripPrefix: typeof stripPrefix;
  stripSuffix: typeof stripSuffix;
  subtract: typeof subtract;
  sum: typeof sum;
  sumBy: typeof sumBy;
  sumOfSquares: typeof sumOfSquares;
  sumOfTwo: typeof sumOfTwo;
  surfaceAreaCone: typeof surfaceAreaCone;
  surfaceAreaCube: typeof surfaceAreaCube;
  surfaceAreaCylinder: typeof surfaceAreaCylinder;
  surfaceAreaPyramidSquare: typeof surfaceAreaPyramidSquare;
  surfaceAreaRectPrism: typeof surfaceAreaRectPrism;
  surfaceAreaSphere: typeof surfaceAreaSphere;
  surround: typeof surround;
  swap: typeof swap;
  swapCase: typeof swapCase;
  tail: typeof tail;
  take: typeof take;
  takeRight: typeof takeRight;
  takeUntil: typeof takeUntil;
  takeWhile: typeof takeWhile;
  tanDeg: typeof tanDeg;
  tap: typeof tap;
  throttle: typeof throttle;
  times: typeof times;
  toFloat: typeof toFloat;
  toInt: typeof toInt;
  stringMerge: typeof stringMerge;
  interleave: typeof interleave;
  toLower: typeof toLower;
  toNumber: typeof toNumber;
  toPairs: typeof toPairs;
  toSet: typeof toSet;
  toTitleCase: typeof toTitleCase;
  toTitleCaseWords: typeof toTitleCaseWords;
  toUpper: typeof toUpper;
  triangleWave: typeof triangleWave;
  triangularNumber: typeof triangularNumber;
  trim: typeof trim;
  trimEnd: typeof trimEnd;
  trimStart: typeof trimStart;
  truncate: typeof truncate;
  tryCatch: typeof tryCatch;
  turnToDeg: typeof turnToDeg;
  turnToRad: typeof turnToRad;
  union: typeof union;
  unionBy: typeof unionBy;
  uniq: typeof uniq;
  uniqueBy: typeof uniqueBy;
  uniqueSorted: typeof uniqueSorted;
  unmask: typeof unmask;
  unsetPath: typeof unsetPath;
  unzip: typeof unzip;
  values: typeof values;
  variance: typeof variance;
  varianceSample: typeof varianceSample;
  volumeCone: typeof volumeCone;
  volumeCube: typeof volumeCube;
  volumeCylinder: typeof volumeCylinder;
  volumePyramidSquare: typeof volumePyramidSquare;
  volumeRectPrism: typeof volumeRectPrism;
  volumeSphere: typeof volumeSphere;
  words: typeof words;
  wrap: typeof wrap;
  wrapAngle: typeof wrapAngle;
  wrapPi: typeof wrapPi;
  zip: typeof zip;
  zipObject: typeof zipObject;
  zipObjectDeep: typeof zipObjectDeep;
};
export default easyJS;
